name: Deploy Build Folder to Server

on:
  push:
    branches:
      - production  # Jab production branch pe push hoga, tab ye trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Install Node.js & Build Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          cd frontend
          npm install
          npm run build

      - name: 📤 Upload Build Folder to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "frontend/build/*"
          target: "/u768586423/domains/keplerx.digital/public_html/kx/frontend/build"
          strip_components: 2
