name: Deploy KeplerX (Docker Compose)

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy and Rebuild
        run: |
          cd /home/newuser/keplerx
          git fetch origin
          git reset --hard origin/prod
          docker compose up -d --build
          docker image prune -f

