name: Deploy to All Servers

on:
  push:
    branches:
      - production  # Jab production branch pe push hoga, tab ye trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔧 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install Dependencies and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ../backend
          npm install

      - name: 🚀 Deploy to All Servers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_1 }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /u768586423/domains/keplerx.digital/public_html/kx
            git pull origin production
            cd frontend
            npm install
            npm run build
            cd ../backend
            npm install
            pm2 restart all
